# Site settings
title: Chi-I Huang's Blog
email: jasson15@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Knowledge changes nothing, neither does technology. A will does, typically a ridiculous one.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jasson15.github.com" # the base hostname & protocol for your site
twitter_username: jassson15
github_username:  jasson15

# Build settings
markdown: kramdown
permalink: pretty
